version: '3.4'

services:
  db-mysql8:
    image: mysql:8.0.25
    container_name: mysql8
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    restart: always

  monpikas:
    image: pavilonis/monpikas:2.0-SNAPSHOT
    container_name: monpikas
    volumes:
      - ./keystore:/usr/app/keystore
      - ./logs:/usr/app/logs
    depends_on:
      - db-mysql8
    ports:
      - "8080:8080"
    links:
      - "db-mysql8:database"
    environment:
      - "JAVA_OPTS=-Dserver.port=8080 -Djdbc.url=jdbc:mysql://db-mysql8:3306/monpikas -Djdbc.username=root -Djdbc.password=1234 -Dlogging.level=INFO -Duser.supervisor.organizationRole=Teacher -Dkey-store-password=SorostaKnistineti -Dkey-store-type=JKS -Dkey-store-file=keystore/reg.taekwondo.lt.jks"
    restart: always