version: '3.4'

services:
  db-mysql8:
    image: mysql:8.0.25
    container_name: mysql8
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - C:\Users\arturas\dumps:/dumps
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    restart: always

  monpikas:
    image: pavilonis/monpikas
    container_name: monpikas
    depends_on:
        - db-mysql8
    ports:
      - "8080:8080"
    links:
      - "db-mysql8:database"
    environment:
      - "JAVA_OPTS=-Dserver.port=8080 -Djdbc.url=jdbc:mysql://db-mysql8:3306/monpikas -Djdbc.username=root -Djdbc.password=1234 -Dlogging.level=INFO -Duser.supervisor.organizationRole=Teacher"
    restart: always