ALTER TABLE ReceiptItem CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE TechCardSet CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE TechCard CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE Product CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE ProductGroup CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE Supplier CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE TechCardGroup CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;

ALTER TABLE TechCardSetType CONVERT TO CHARACTER SET utf8
COLLATE utf8_general_ci;
