logging:
  level:
    root: ${logging.level}
  file:
    path: logs

spring:
  datasource:
    url: ${jdbc.url}?characterEncoding=UTF-8
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
    test-on-borrow: true
    test-while-idle: true
    validation-interval: 10000
    time-between-eviction-runs-millis: 60000
    tomcat:
      max-active: 100
      max-idle: 35
      max-wait: -1

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES