ALTER TABLE Meal ADD COLUMN startTime2 SMALLINT NOT NULL;
ALTER TABLE Meal ADD COLUMN endTime2 SMALLINT NOT NULL;

UPDATE Meal
SET startTime2 = TIME_TO_SEC(startTime) / 60;

UPDATE Meal
SET endTime2 = TIME_TO_SEC(endTime) / 60;

ALTER TABLE Meal DROP COLUMN startTime;
ALTER TABLE Meal DROP COLUMN endTime;

ALTER TABLE Meal CHANGE COLUMN startTime2 startTime SMALLINT NOT NULL;
ALTER TABLE Meal CHANGE COLUMN endTime2 endTime SMALLINT NOT NULL;